# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: BBBBBreaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: NNNNNNExciting New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: NNNNNOther Changes
      labels:
        - "*"
